USE [isTakipDB]
GO

/****** Object:  Table [dbo].[TBL_LOGLAR]    Script Date: 12/08/2024 16:28:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_LOGLAR](
	[logID] [int] IDENTITY(1,1) NOT NULL,
	[logAciklama] [nvarchar](max) NULL,
	[actionAd] [nvarchar](50) NULL,
	[controllerAd] [nvarchar](50) NULL,
	[tarih] [datetime] NULL,
	[personelID] [int] NULL,
 CONSTRAINT [PK_TBL_LOGLAR] PRIMARY KEY CLUSTERED 
(
	[logID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_LOGLAR]  WITH CHECK ADD  CONSTRAINT [FK_TBL_LOGLAR_TBL_PERSONELLER] FOREIGN KEY([personelID])
REFERENCES [dbo].[TBL_PERSONELLER] ([personelID])
GO

ALTER TABLE [dbo].[TBL_LOGLAR] CHECK CONSTRAINT [FK_TBL_LOGLAR_TBL_PERSONELLER]
GO


