USE [isTakipDB]
GO

/****** Object:  Table [dbo].[TBL_MAILLER]    Script Date: 12/08/2024 16:28:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_MAILLER](
	[mailID] [int] IDENTITY(1,1) NOT NULL,
	[mailGonderen] [int] NULL,
	[mailAlici] [int] NULL,
	[mailKonu] [nvarchar](max) NULL,
	[mailIcerik] [nvarchar](max) NULL,
	[mailOkunma] [bit] NULL,
	[mailGonderimTarihi] [datetime] NULL,
	[mailArsiv] [bit] NULL,
	[mailDeletionDate] [datetime] NULL,
	[mailAktiflik] [bit] NULL,
	[mailCopKutusu] [bit] NULL,
 CONSTRAINT [PK_TBL_MAILLER] PRIMARY KEY CLUSTERED 
(
	[mailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_MAILLER]  WITH CHECK ADD  CONSTRAINT [FK_TBL_MAILLER_TBL_PERSONELLER] FOREIGN KEY([mailGonderen])
REFERENCES [dbo].[TBL_PERSONELLER] ([personelID])
GO

ALTER TABLE [dbo].[TBL_MAILLER] CHECK CONSTRAINT [FK_TBL_MAILLER_TBL_PERSONELLER]
GO

ALTER TABLE [dbo].[TBL_MAILLER]  WITH CHECK ADD  CONSTRAINT [FK_TBL_MAILLER_TBL_PERSONELLER1] FOREIGN KEY([mailAlici])
REFERENCES [dbo].[TBL_PERSONELLER] ([personelID])
GO

ALTER TABLE [dbo].[TBL_MAILLER] CHECK CONSTRAINT [FK_TBL_MAILLER_TBL_PERSONELLER1]
GO


