//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class isTakipDBEntities : DbContext
    {
        public isTakipDBEntities()
            : base("name=isTakipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_BIRIMLER> TBL_BIRIMLER { get; set; }
        public virtual DbSet<TBL_DURUMLAR> TBL_DURUMLAR { get; set; }
        public virtual DbSet<TBL_ISLER> TBL_ISLER { get; set; }
        public virtual DbSet<TBL_PERSONELLER> TBL_PERSONELLER { get; set; }
        public virtual DbSet<TBL_YETKITURLER> TBL_YETKITURLER { get; set; }
        public virtual DbSet<TBL_LOGLAR> TBL_LOGLAR { get; set; }
        public virtual DbSet<YemekTablo> YemekTablo { get; set; }
        public virtual DbSet<TBL_DUYURULAR> TBL_DUYURULAR { get; set; }
        public virtual DbSet<TBL_MAILLER> TBL_MAILLER { get; set; }
        public virtual DbSet<TBL_IZINLER> TBL_IZINLER { get; set; }
    }
}
