//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DURUMLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DURUMLAR()
        {
            this.TBL_ISLER = new HashSet<TBL_ISLER>();
        }
    
        public int durumID { get; set; }
        public string durumAd { get; set; }
        public Nullable<System.DateTime> durumCreationDate { get; set; }
        public Nullable<bool> durumAktiflik { get; set; }
        public Nullable<System.DateTime> durumDeletionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ISLER> TBL_ISLER { get; set; }
    }
}
