//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_YETKITURLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_YETKITURLER()
        {
            this.TBL_PERSONELLER = new HashSet<TBL_PERSONELLER>();
        }
    
        public int yetkiTurID { get; set; }
        public string yetkiTurAd { get; set; }
        public Nullable<System.DateTime> yetkiTurCreationDate { get; set; }
        public Nullable<System.DateTime> yetkiTurDeletionDate { get; set; }
        public Nullable<bool> yetkiTurAktiflik { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PERSONELLER> TBL_PERSONELLER { get; set; }
    }
}
