//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ISLER
    {
        public int isID { get; set; }
        public string isBaslik { get; set; }
        public string isAciklama { get; set; }
        public Nullable<int> isPersonelID { get; set; }
        public Nullable<System.DateTime> iletilenTarih { get; set; }
        public Nullable<System.DateTime> yapilanTarih { get; set; }
        public Nullable<int> isDurumID { get; set; }
        public string isYorum { get; set; }
        public Nullable<System.DateTime> isCreationDate { get; set; }
        public Nullable<System.DateTime> isDeletionDate { get; set; }
        public Nullable<bool> isAktiflik { get; set; }
        public Nullable<System.DateTime> isKabulEdilenTarih { get; set; }
        public Nullable<System.DateTime> isReddedilenTarih { get; set; }
    
        public virtual TBL_DURUMLAR TBL_DURUMLAR { get; set; }
        public virtual TBL_PERSONELLER TBL_PERSONELLER { get; set; }
    }
}
