//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DUYURULAR
    {
        public int duyuruID { get; set; }
        public string duyuruBaslik { get; set; }
        public string duyuruIcerik { get; set; }
        public Nullable<System.DateTime> duyuruTarih { get; set; }
        public Nullable<int> duyuruOlusturan { get; set; }
        public Nullable<bool> duyuruAktiflik { get; set; }
        public Nullable<System.DateTime> duyuruCreationDate { get; set; }
        public Nullable<System.DateTime> duyuruDeletionDate { get; set; }
        public Nullable<int> duyuruOlusturanBirim { get; set; }
    
        public virtual TBL_PERSONELLER TBL_PERSONELLER { get; set; }
    }
}
