//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONELLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PERSONELLER()
        {
            this.TBL_ISLER = new HashSet<TBL_ISLER>();
            this.TBL_LOGLAR = new HashSet<TBL_LOGLAR>();
            this.TBL_DUYURULAR = new HashSet<TBL_DUYURULAR>();
            this.TBL_MAILLER = new HashSet<TBL_MAILLER>();
            this.TBL_MAILLER1 = new HashSet<TBL_MAILLER>();
            this.TBL_IZINLER = new HashSet<TBL_IZINLER>();
        }
    
        public int personelID { get; set; }
        public string personelAdSoyad { get; set; }
        public string personelKullaniciAdi { get; set; }
        public string personelParola { get; set; }
        public string personelFoto { get; set; }
        public Nullable<int> personelBirimID { get; set; }
        public Nullable<int> personelYetkiTurID { get; set; }
        public Nullable<bool> yeniPersonel { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public Nullable<System.DateTime> personelCreationDate { get; set; }
        public Nullable<System.DateTime> personelDeletionDate { get; set; }
        public Nullable<System.DateTime> personelDogumTarihi { get; set; }
        public string mailAdresi { get; set; }
        public string telefonNumarasi { get; set; }
        public Nullable<int> personelIzinGun { get; set; }
    
        public virtual TBL_BIRIMLER TBL_BIRIMLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ISLER> TBL_ISLER { get; set; }
        public virtual TBL_YETKITURLER TBL_YETKITURLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_LOGLAR> TBL_LOGLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DUYURULAR> TBL_DUYURULAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MAILLER> TBL_MAILLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MAILLER> TBL_MAILLER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_IZINLER> TBL_IZINLER { get; set; }
    }
}
