//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_LOGLAR
    {
        public int logID { get; set; }
        public string logAciklama { get; set; }
        public string actionAd { get; set; }
        public string controllerAd { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> personelID { get; set; }
    
        public virtual TBL_PERSONELLER TBL_PERSONELLER { get; set; }
    }
}
