//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_IZINLER
    {
        public int izinID { get; set; }
        public Nullable<int> izinPersonelID { get; set; }
        public Nullable<System.DateTime> izinBaslangicTarihi { get; set; }
        public Nullable<System.DateTime> izinBitisTarihi { get; set; }
        public Nullable<bool> izinOnay { get; set; }
        public Nullable<System.DateTime> izinTalepTarihi { get; set; }
        public Nullable<bool> izinRed { get; set; }
        public Nullable<int> izinGunuSayisi { get; set; }
        public Nullable<System.DateTime> izinDegerlendirmeTarihi { get; set; }
    
        public virtual TBL_PERSONELLER TBL_PERSONELLER { get; set; }
    }
}
