//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MAILLER
    {
        public int mailID { get; set; }
        public Nullable<int> mailGonderen { get; set; }
        public Nullable<int> mailAlici { get; set; }
        public string mailKonu { get; set; }
        public string mailIcerik { get; set; }
        public Nullable<bool> mailOkunma { get; set; }
        public Nullable<System.DateTime> mailGonderimTarihi { get; set; }
        public Nullable<bool> mailArsiv { get; set; }
        public Nullable<System.DateTime> mailDeletionDate { get; set; }
        public Nullable<bool> mailAktiflik { get; set; }
        public Nullable<bool> mailCopKutusu { get; set; }
    
        public virtual TBL_PERSONELLER TBL_PERSONELLER { get; set; }
        public virtual TBL_PERSONELLER TBL_PERSONELLER1 { get; set; }
    }
}
