//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakipSistemiMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YemekTablo
    {
        public int MenuId { get; set; }
        public string YemekAdi1 { get; set; }
        public string YemekAdi2 { get; set; }
        public string YemekAdi3 { get; set; }
        public string YemekAdi4 { get; set; }
        public string YemekAdi5 { get; set; }
        public string YemekAdi6 { get; set; }
        public string YemekAdi7 { get; set; }
        public string YemekAdi8 { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> Kalori1 { get; set; }
        public Nullable<int> Kalori2 { get; set; }
        public Nullable<int> Kalori3 { get; set; }
        public Nullable<int> Kalori4 { get; set; }
        public Nullable<int> Kalori5 { get; set; }
        public Nullable<int> Kalori6 { get; set; }
        public Nullable<int> Kalori7 { get; set; }
        public Nullable<int> Kalori8 { get; set; }
    }
}
